apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
spec:
  containers:
    - name: demo-container
      image: probe-demo
      imagePullPolicy: Never
      ports:
        - containerPort: 3000

      startupProbe:
        httpGet:
          path: /startup
          port: 3000
        failureThreshold: 10
        periodSeconds: 1

      livenessProbe:
        httpGet:
          path: /health
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 5

      readinessProbe:
        httpGet:
          path: /ready
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 5
